### ISSUE TITLE
Trouble making multiple channels to same peer

### ISSUE THREAD

**Issue by futurepaul** [Mutiny-Wallet/mutiny-node#280]
Things get pretty wonky when I try to open multiple channels to same peer

It looks like it's working at first but then they disappear, they also disappear on refresh. Maybe something related to redundant peer connections?

![Screen Shot 2022-12-30 at 3 14 01 PM](https://user-images.githubusercontent.com/543668/210112134-71b63001-ec06-4f14-a9e3-de8569bfafb7.png)

**Comment by benthecarman** [comment]
I don't think ldk supports this

**Comment by TonyGiorgio** [comment]
This is more than likely some websocket flackiness that I've still seen, I'll open a ticket for that seperately but I have confirmed that multiple channels to the same peer are working just fine.

![Screenshot from 2023-01-31 15-36-28](https://user-images.githubusercontent.com/101225832/215889152-99e34cee-e918-4165-9a25-a42d5e9fc3fe.png)
